// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EvenService exposes the supported G2 operations to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearDashboardSchedule(experimental: boolean): $CancellablePromise<void> {
    return $Call.ByID(2708506403, experimental);
}

/**
 * ClearDisplay closes the active native page without switching to teleprompter mode.
 */
export function ClearDisplay(): $CancellablePromise<void> {
    return $Call.ByID(4277348724);
}

export function CodexStatus(): $CancellablePromise<$models.CodexStatus> {
    return $Call.ByID(1370259554);
}

export function ConfigureDashboard(widgetOrder: number[] | null, halfDay: boolean, celsius: boolean, experimental: boolean): $CancellablePromise<void> {
    return $Call.ByID(2013049673, widgetOrder, halfDay, celsius, experimental);
}

export function Connect(): $CancellablePromise<$models.DeviceStatus> {
    return $Call.ByID(3372429189);
}

export function ConnectDevice(leftAddress: string, rightAddress: string): $CancellablePromise<$models.DeviceStatus> {
    return $Call.ByID(1786707667, leftAddress, rightAddress);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1239481831);
}

/**
 * LensCalibration pushes the self-describing calibration list and returns it, so
 * the desktop can show the same rows.
 * 
 * It measures the two numbers the whole layout is built on — how wide a row may
 * be and how many rows fit — plus which candidate glyphs the firmware actually
 * renders; see calibrationRows for how to read the result back. It reuses the
 * status container on purpose, so the next status push simply replaces it.
 */
export function LensCalibration(): $CancellablePromise<string[] | null> {
    return $Call.ByID(567394971);
}

/**
 * PreviewPage returns the actual page model for rendering inside the Wails
 * window. JSON keeps the external g2 structs out of generated TypeScript types.
 */
export function PreviewPage(): $CancellablePromise<string> {
    return $Call.ByID(2583055872);
}

export function PushDashboardSchedule(items: $models.DashboardScheduleItem[] | null, experimental: boolean): $CancellablePromise<void> {
    return $Call.ByID(2296762246, items, experimental);
}

export function RequestDeviceSettings(): $CancellablePromise<$models.DeviceSettings> {
    return $Call.ByID(2455142085);
}

/**
 * ScanCandidates discovers every nearby arm so the frontend can explicitly
 * pair one left and one right device when multiple glasses are present.
 */
export function ScanCandidates(): $CancellablePromise<$models.DeviceCandidate[] | null> {
    return $Call.ByID(3455048670);
}

export function SetBrightness(level: number, automatic: boolean): $CancellablePromise<void> {
    return $Call.ByID(3899436, level, automatic);
}

/**
 * SetDisplayDuration controls how long every successful display write remains
 * visible. Changing it also restarts the timer for content already on screen.
 */
export function SetDisplayDuration(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(208460827, seconds);
}

export function SetHeadUp(enabled: boolean, angle: number): $CancellablePromise<void> {
    return $Call.ByID(1617599880, enabled, angle);
}

export function SetScreenPosition(height: number, depth: number): $CancellablePromise<void> {
    return $Call.ByID(1079501688, height, depth);
}

export function ShowDashboard(): $CancellablePromise<void> {
    return $Call.ByID(3886324124);
}

/**
 * ShowImage decodes a browser data URL or plain base64 image and streams it
 * through the SDK's full-lens 4-bit image renderer.
 */
export function ShowImage(encoded: string): $CancellablePromise<void> {
    return $Call.ByID(1894971909, encoded);
}

export function ShowList(rows: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2326881440, rows);
}

export function ShowNativeText(text: string): $CancellablePromise<void> {
    return $Call.ByID(1496040276, text);
}

export function ShowTeleprompter(text: string): $CancellablePromise<void> {
    return $Call.ByID(1227538937, text);
}

export function StartMicrophone(): $CancellablePromise<void> {
    return $Call.ByID(2464660827);
}

/**
 * StartNativeSimulator opens the official desktop simulator only after the
 * user explicitly requests it from the embedded preview toolbar.
 */
export function StartNativeSimulator(): $CancellablePromise<void> {
    return $Call.ByID(358782026);
}

export function Status(): $CancellablePromise<$models.DeviceStatus> {
    return $Call.ByID(1050895539);
}

export function StopMicrophone(): $CancellablePromise<void> {
    return $Call.ByID(2172515725);
}
