// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodexStatus describes the hook-backed desktop status bridge.
 * 
 * The name is kept for backwards compatibility with the generated Wails
 * bindings: it now aggregates every configured agent source.
 */
export interface CodexStatus {
    "available": boolean;
    "message": string;

    /**
     * State is the raw hook state of the session that currently owns the
     * glasses ("thinking", "needs_input", ...). The desktop uses it to show the
     * same loading sweep the lens is showing, so the preview carries the motion
     * and not only the text.
     */
    "state": string;

    /**
     * Rows is exactly what the glasses are showing: the composed list for the
     * most recently active session. The desktop panel renders it verbatim so
     * the content can be reviewed without wearing the device.
     */
    "rows": string[] | null;
}

export interface DashboardScheduleItem {
    "id": number;
    "title": string;
    "location": string;
    "time": string;
    "endTimestamp": number;
}

export interface DeviceCandidate {
    "arm": string;
    "address": string;
    "name": string;
    "rssi": number;
}

export interface DeviceCapabilities {
    "text": boolean;
    "nativeText": boolean;
    "nativeList": boolean;
    "image": boolean;
    "microphoneLC3": boolean;
    "inputEvents": boolean;
    "deviceSettings": boolean;
    "brightness": boolean;
    "headUp": boolean;
    "screenPosition": boolean;
    "dashboard": boolean;
}

export interface DeviceEvent {
    "kind": string;
    "name": string;
    "itemName": string;
    "type": string;
    "itemIndex": number;
}

export interface DeviceSettings {
    "batteryPercent": number;
    "charging": boolean;
    "leftFirmwareVersion": string;
    "rightFirmwareVersion": string;
    "brightness": number;
    "autoBrightness": boolean;
    "headUpEnabled": boolean;
    "headUpAngle": number;
    "wearDetection": boolean;
    "silentMode": boolean;
    "screenDepth": number;
    "screenHeight": number;
}

/**
 * DeviceStatus is the connection state displayed by the desktop client.
 */
export interface DeviceStatus {
    "connected": boolean;
    "connecting": boolean;
    "leftState": string;
    "rightState": string;
    "lastError": string;
    "lastErrorAt": string;
    "reconnectCount": number;
    "displayDurationSeconds": number;
    "deviceId": string;
    "deviceName": string;
    "audioAvailable": boolean;
    "settingsKnown": boolean;
    "capabilities": DeviceCapabilities;
    "settings": DeviceSettings;
    "audioActive": boolean;
    "audioFrames": number;
    "audioBytes": number;
    "lastEvent": DeviceEvent;
}
